spring:
  security:
    user:
      name: admin
      password: 1234
  datasource:
    url: jdbc:mysql://localhost:3306/health?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
server:
  port: 10086
